# Generated by Django 2.2.6 on 2019-10-22 13:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191021_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
